"""init

Revision ID: ec6a92d30b59
Revises: 
Create Date: 2026-07-27 12:47:07.953035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6a92d30b59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_pages_deleted_at'), 'contact_pages', ['deleted_at'], unique=False)
    op.create_table('expert_service_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_expert_service_definitions_deleted_at'), 'expert_service_definitions', ['deleted_at'], unique=False)
    op.create_table('expert_tag_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_expert_tag_definitions_deleted_at'), 'expert_tag_definitions', ['deleted_at'], unique=False)
    op.create_table('experts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_wechat', sa.String(length=100), nullable=True),
    sa.Column('platform_count', sa.Integer(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_deleted_at'), 'experts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_experts_is_published'), 'experts', ['is_published'], unique=False)
    op.create_index(op.f('ix_experts_name'), 'experts', ['name'], unique=False)
    op.create_table('forum_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['forum_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_categories_deleted_at'), 'forum_categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_forum_categories_slug'), 'forum_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('expert_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_cases_deleted_at'), 'expert_cases', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expert_cases_expert_id'), 'expert_cases', ['expert_id'], unique=False)
    op.create_table('expert_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('platform_type', sa.String(length=50), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('blogger_name', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_platforms_deleted_at'), 'expert_platforms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expert_platforms_expert_id'), 'expert_platforms', ['expert_id'], unique=False)
    op.create_table('expert_services',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['expert_service_definitions.id'], ),
    sa.PrimaryKeyConstraint('expert_id', 'service_id')
    )
    op.create_table('expert_tags',
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['expert_tag_definitions.id'], ),
    sa.PrimaryKeyConstraint('expert_id', 'tag_id')
    )
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['forum_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_category_id'), 'forum_posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_deleted_at'), 'forum_posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_forum_posts_status'), 'forum_posts', ['status'], unique=False)
    op.create_index(op.f('ix_forum_posts_title'), 'forum_posts', ['title'], unique=False)
    op.create_index(op.f('ix_forum_posts_user_id'), 'forum_posts', ['user_id'], unique=False)
    op.create_table('interaction_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['interaction_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_comments_deleted_at'), 'interaction_comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interaction_comments_target_id'), 'interaction_comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_interaction_comments_target_type'), 'interaction_comments', ['target_type'], unique=False)
    op.create_index(op.f('ix_interaction_comments_user_id'), 'interaction_comments', ['user_id'], unique=False)
    op.create_table('interaction_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_user_target_like')
    )
    op.create_index(op.f('ix_interaction_likes_deleted_at'), 'interaction_likes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_interaction_likes_target_id'), 'interaction_likes', ['target_id'], unique=False)
    op.create_index(op.f('ix_interaction_likes_target_type'), 'interaction_likes', ['target_type'], unique=False)
    op.create_index(op.f('ix_interaction_likes_user_id'), 'interaction_likes', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_logo', sa.String(length=500), nullable=True),
    sa.Column('salary_text', sa.String(length=100), nullable=False, comment='e.g. "20K-35K·14薪"'),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False, comment='全职/兼职/实习'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True, comment='["五险一金", "年终奖"]'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='[{"type": "internal", "label": "内推", "color": "#FF6B6B"}]'),
    sa.Column('contact_expert_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False, comment='Default contact expert ID (1)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_expert_id'], ['experts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_contact_expert_id'), 'jobs', ['contact_expert_id'], unique=False)
    op.create_index(op.f('ix_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_jobs_industry'), 'jobs', ['industry'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_is_featured'), 'jobs', ['is_featured'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('forum_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_replies_deleted_at'), 'forum_replies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_forum_replies_post_id'), 'forum_replies', ['post_id'], unique=False)
    op.create_index(op.f('ix_forum_replies_user_id'), 'forum_replies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_replies_user_id'), table_name='forum_replies')
    op.drop_index(op.f('ix_forum_replies_post_id'), table_name='forum_replies')
    op.drop_index(op.f('ix_forum_replies_deleted_at'), table_name='forum_replies')
    op.drop_table('forum_replies')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_featured'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_industry'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_deleted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_contact_expert_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_interaction_likes_user_id'), table_name='interaction_likes')
    op.drop_index(op.f('ix_interaction_likes_target_type'), table_name='interaction_likes')
    op.drop_index(op.f('ix_interaction_likes_target_id'), table_name='interaction_likes')
    op.drop_index(op.f('ix_interaction_likes_deleted_at'), table_name='interaction_likes')
    op.drop_table('interaction_likes')
    op.drop_index(op.f('ix_interaction_comments_user_id'), table_name='interaction_comments')
    op.drop_index(op.f('ix_interaction_comments_target_type'), table_name='interaction_comments')
    op.drop_index(op.f('ix_interaction_comments_target_id'), table_name='interaction_comments')
    op.drop_index(op.f('ix_interaction_comments_deleted_at'), table_name='interaction_comments')
    op.drop_table('interaction_comments')
    op.drop_index(op.f('ix_forum_posts_user_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_title'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_status'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_deleted_at'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_category_id'), table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_table('expert_tags')
    op.drop_table('expert_services')
    op.drop_index(op.f('ix_expert_platforms_expert_id'), table_name='expert_platforms')
    op.drop_index(op.f('ix_expert_platforms_deleted_at'), table_name='expert_platforms')
    op.drop_table('expert_platforms')
    op.drop_index(op.f('ix_expert_cases_expert_id'), table_name='expert_cases')
    op.drop_index(op.f('ix_expert_cases_deleted_at'), table_name='expert_cases')
    op.drop_table('expert_cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forum_categories_slug'), table_name='forum_categories')
    op.drop_index(op.f('ix_forum_categories_deleted_at'), table_name='forum_categories')
    op.drop_table('forum_categories')
    op.drop_index(op.f('ix_experts_name'), table_name='experts')
    op.drop_index(op.f('ix_experts_is_published'), table_name='experts')
    op.drop_index(op.f('ix_experts_deleted_at'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_expert_tag_definitions_deleted_at'), table_name='expert_tag_definitions')
    op.drop_table('expert_tag_definitions')
    op.drop_index(op.f('ix_expert_service_definitions_deleted_at'), table_name='expert_service_definitions')
    op.drop_table('expert_service_definitions')
    op.drop_index(op.f('ix_contact_pages_deleted_at'), table_name='contact_pages')
    op.drop_table('contact_pages')
    # ### end Alembic commands ###
